# Setup

In [1]:
from __future__ import division, print_function, unicode_literals
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
from sklearn.datasets import fetch_california_housing

# Gradient Descent

Gradient: <https://www.youtube.com/watch?v=npkl19rcpdY>

# Linear Regression 

In [16]:
SK_DATA_HOME="datasets/"
housing = fetch_california_housing(data_home=SK_DATA_HOME)

downloading Cal. housing from http://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.tgz to datasets/


In [17]:
housing.feature_names

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [18]:
m, n = housing.data.shape
m, n

(20640, 8)

In [19]:
housing.data[:1], housing.target[:1]

(array([[   8.3252    ,   41.        ,    6.98412698,    1.02380952,
          322.        ,    2.55555556,   37.88      , -122.23      ]]),
 array([ 4.526]))

## Scale 

In [20]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_housing_data = scaler.fit_transform(housing.data)
# add bias
scaled_housing_data_plus_bias = np.c_[np.ones((m, 1)), scaled_housing_data]
print(scaled_housing_data_plus_bias)

[[ 1.          2.34476576  0.98214266 ..., -0.04959654  1.05254828
  -1.32783522]
 [ 1.          2.33223796 -0.60701891 ..., -0.09251223  1.04318455
  -1.32284391]
 [ 1.          1.7826994   1.85618152 ..., -0.02584253  1.03850269
  -1.33282653]
 ..., 
 [ 1.         -1.14259331 -0.92485123 ..., -0.0717345   1.77823747
  -0.8237132 ]
 [ 1.         -1.05458292 -0.84539315 ..., -0.09122515  1.77823747
  -0.87362627]
 [ 1.         -0.78012947 -1.00430931 ..., -0.04368215  1.75014627
  -0.83369581]]


![title](img/eq_86.png)

In [9]:
tf.reset_default_graph()
X = tf.constant(scaled_housing_data_plus_bias, dtype=tf.float32, name="X")
y = tf.constant(housing.target.reshape(-1, 1), dtype=tf.float32, name="y")
theta = tf.Variable(tf.random_uniform([n + 1, 1], -1.0, 1.0), name="theta")
y_pred = tf.matmul(X, theta, name="predictions")
error = y_pred - y 
mse = tf.reduce_mean(tf.square(error), name="mse")

![title](img/eq_123.png)

![title](img/eq_125.png)

In [11]:
gradients = 2/m * tf.matmul(tf.transpose(X), error)
# gradients = tf.gradients(mse, [theta])[0]

![title](img/eq_132.png)

In [12]:
learning_rate = 0.01
training_op = tf.assign(theta, theta - learning_rate * gradients)
#optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate)
#training_op = optimizer.minimize(mse)

In [15]:
init = tf.initialize_all_variables()

n_epochs = 1000

with tf.Session() as sess:
    sess.run(init)
    print("===Initial theta===")
    init_theta = theta.eval()
    print(init_theta)
    
    print("===Start training===")
    for epoch in range(n_epochs):
        if epoch % 100 == 0:
            print("Epoch", epoch, "MSE =", mse.eval())
        sess.run(training_op)
    
    print("===Final theta===")
    best_theta = theta.eval()
    print(best_theta)

===Initial theta===
[[ 0.72533917]
 [ 0.16568065]
 [-0.88386583]
 [ 0.46327353]
 [-0.89875078]
 [ 0.67488456]
 [-0.7472744 ]
 [ 0.65740609]
 [-0.33021855]]
===Start training===
Epoch 0 MSE = 6.28909
Epoch 100 MSE = 0.831775
Epoch 200 MSE = 0.697058
Epoch 300 MSE = 0.648056
Epoch 400 MSE = 0.613625
Epoch 500 MSE = 0.588802
Epoch 600 MSE = 0.570888
Epoch 700 MSE = 0.557958
Epoch 800 MSE = 0.548623
Epoch 900 MSE = 0.541882
===Final theta===
[[ 2.06855249]
 [ 0.77947813]
 [ 0.15343565]
 [-0.08833711]
 [ 0.12291335]
 [ 0.00876513]
 [-0.04119111]
 [-0.69413167]
 [-0.65496218]]


# MNIST

![title](img/mnist.png)

In [2]:
from tensorflow.examples.tutorials.mnist import input_data
mnist_tf = input_data.read_data_sets("datasets/MNIST_data/", one_hot=True)

Extracting datasets/MNIST_data/train-images-idx3-ubyte.gz
Extracting datasets/MNIST_data/train-labels-idx1-ubyte.gz
Extracting datasets/MNIST_data/t10k-images-idx3-ubyte.gz
Extracting datasets/MNIST_data/t10k-labels-idx1-ubyte.gz


In [22]:
mnist_tf.train.images.shape, mnist_tf.train.labels.shape

((55000, 784), (55000, 10))

In [23]:
mnist_tf.train.next_batch(10)

(array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]], dtype=float32),
 array([[ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
        [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
        [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]))

# Softmax Classification

![title](img/nn-diag.png)

![title](img/nn-matrix.png)

In [3]:
tf.reset_default_graph()

X = tf.placeholder(tf.float32, [None, 784])
Y = tf.placeholder(tf.float32, [None, 10])

W = tf.Variable(tf.zeros([784, 10]))
b = tf.Variable(tf.zeros([10]))

Y_predict = tf.nn.softmax(tf.matmul(X, W) + b)

![title](img/cross_entropy.png)

In [4]:
cross_entropy_loss = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(Y_predict), reduction_indices=[1]))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.5)
training_op = optimizer.minimize(cross_entropy_loss)

In [5]:
# evaluate
correction_prediction = tf.equal(tf.argmax(Y, 1), tf.argmax(Y_predict, 1))
accuracy = tf.reduce_mean(tf.cast(correction_prediction, tf.float32))

In [8]:
init = tf.initialize_all_variables()

with tf.Session() as sess:
    sess.run(init)
    for i in range(1001):
        batch_xs, batch_ys = mnist_tf.train.next_batch(100)
        sess.run(training_op, feed_dict={X: batch_xs, Y: batch_ys})
        if i % 100 == 0:
            print("accuracy:", sess.run(accuracy, feed_dict={X: mnist_tf.test.images, Y: mnist_tf.test.labels}))

accuracy: 0.1126
accuracy: 0.8936
accuracy: 0.906
accuracy: 0.91
accuracy: 0.9105
accuracy: 0.9139
accuracy: 0.9169
accuracy: 0.9118
accuracy: 0.9174
accuracy: 0.9188
accuracy: 0.9186


# Neural Network

In [79]:
from tensorflow.contrib.layers import fully_connected

# or implement layer by yourself
def neuron_layer(X, n_neurons, name, activation=None):
    with tf.name_scope(name):
        n_inputs = int(X.get_shape()[1])
        stddev = 2 / np.sqrt(n_inputs)
        init_w = tf.truncated_normal((n_inputs, n_neurons), stddev=stddev)
        W = tf.Variable(init_w, name="weights")
        b = tf.Variable(tf.zeros([n_neurons]), name="biases")
        z = tf.matmul(X, W) + b
        if activation == "relu":
            return tf.nn.relu(z)
        else:
            return z

In [80]:
tf.reset_default_graph()

from tensorflow.contrib.layers import fully_connected

n_inputs = 28 * 28 #784
n_hidden1 = 300
n_hidden2 = 100
n_outputs = 10
learning_rate = 0.01

# input & target
X = tf.placeholder(tf.float32, [None, n_inputs], name="X")
Y = tf.placeholder(tf.int32, [None, n_outputs], name='Y')

# with tf.name_scope("nn"):
#     hidden = fully_connected(X, 150, scope="hidden", 
#                              activation_fn=tf.sigmoid)
#     outputs = fully_connected(hidden, n_outputs, scope="outputs",
#                               activation_fn=None)

# with tf.name_scope("dnn"):
#     hidden1 = neuron_layer(X, n_hidden1, "hidden1", activation="relu")
#     hidden2 = neuron_layer(hidden1, n_hidden2, "hidden2", activation="relu")
#     outputs = neuron_layer(hidden2, n_outputs, "output")
    
with tf.name_scope("dnn"):
    hidden1 = fully_connected(X, n_hidden1, scope="hidden1")
    hidden2 = fully_connected(hidden1, n_hidden2, scope="hidden2")
    outputs = fully_connected(hidden2, n_outputs, scope="outputs",
                             activation_fn=None)
    
with tf.name_scope("loss"):
    xentropy = tf.nn.softmax_cross_entropy_with_logits(outputs, Y)
    loss = tf.reduce_mean(xentropy, name="loss")

with tf.name_scope("train"):
    #optimizer = tf.train.GradientDescentOptimizer(learning_rate)
    optimizer = tf.train.AdamOptimizer(learning_rate)
    training_op = optimizer.minimize(loss)

with tf.name_scope("eval"):
    correct = tf.equal(tf.argmax(Y, 1), tf.argmax(outputs, 1))
    accuracy = tf.reduce_mean(tf.cast(correct, tf.float32))
    
init = tf.initialize_all_variables()

In [81]:
from datetime import datetime

now = datetime.utcnow().strftime("%Y%m%d%H%M%S")
root_logdir = "tf_logs"
logdir = "{}/run-{}/".format(root_logdir, now)
xentropy_summary = tf.scalar_summary('Cross Entropy Loss', loss)
summary_writer = tf.train.SummaryWriter(logdir, tf.get_default_graph())

In [83]:
n_epochs = 20
batch_size = 128
n_batches = mnist_tf.train.num_examples // batch_size

with tf.Session() as sess:
    init.run()
    for epoch in range(n_epochs):
        for iteration in range(n_batches):
            X_batch, Y_batch = mnist_tf.train.next_batch(batch_size)
            sess.run(training_op, feed_dict={X: X_batch, Y: Y_batch})
        summary_str = xentropy_summary.eval(feed_dict={X: X_batch, Y: Y_batch})
        step = epoch * n_batches + iteration
        summary_writer.add_summary(summary_str, step)
        acc_train = accuracy.eval(feed_dict={X: X_batch,
                                             Y: Y_batch})
        acc_test = accuracy.eval(feed_dict={X: mnist_tf.test.images,
                                            Y: mnist_tf.test.labels})
        print(epoch, "Train accuracy: ", acc_train, "Test accuracy: ", acc_test)
    
    summary_writer.close()

0 Train accuracy:  0.92 Test accuracy:  0.9388
1 Train accuracy:  0.98 Test accuracy:  0.9574
2 Train accuracy:  0.98 Test accuracy:  0.9447
3 Train accuracy:  0.96 Test accuracy:  0.9691
4 Train accuracy:  0.98 Test accuracy:  0.9652
5 Train accuracy:  0.96 Test accuracy:  0.967
6 Train accuracy:  0.98 Test accuracy:  0.9598
7 Train accuracy:  1.0 Test accuracy:  0.9726
8 Train accuracy:  1.0 Test accuracy:  0.967
9 Train accuracy:  0.98 Test accuracy:  0.9703
10 Train accuracy:  1.0 Test accuracy:  0.969
11 Train accuracy:  0.98 Test accuracy:  0.9729
12 Train accuracy:  1.0 Test accuracy:  0.9709
13 Train accuracy:  0.98 Test accuracy:  0.9695
14 Train accuracy:  1.0 Test accuracy:  0.9709
15 Train accuracy:  1.0 Test accuracy:  0.9701
16 Train accuracy:  0.98 Test accuracy:  0.9686
17 Train accuracy:  1.0 Test accuracy:  0.9689
18 Train accuracy:  1.0 Test accuracy:  0.9723
19 Train accuracy:  0.98 Test accuracy:  0.9715


## Watch your training result:  
* tensorboard --logdir tf_logs/
* go to http://[your_ip]:6006

# Keras - home work!

In [87]:
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation
from keras.optimizers import Adam
from keras.utils import np_utils


batch_size = 128
n_outputs = 10
n_epochs = 20
learning_rate = 0.01

# the data, shuffled and split between train and test sets
(X_train, y_train), (X_test, y_test) = mnist.load_data()

X_train = X_train.reshape(60000, 784)
X_test = X_test.reshape(10000, 784)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255
print(X_train.shape[0], 'train samples')
print(X_test.shape[0], 'test samples')

# convert class vectors to binary class matrices
Y_train = np_utils.to_categorical(y_train, nb_classes)
Y_test = np_utils.to_categorical(y_test, nb_classes)

model = Sequential()
model.add(Dense(512, input_shape=(784,)))
model.add(Activation('relu'))
model.add(Dropout(0.2))
model.add(Dense(512))
model.add(Activation('relu'))
model.add(Dropout(0.2))
model.add(Dense(10))
model.add(Activation('softmax'))

model.summary()

model.compile(loss='categorical_crossentropy',
              optimizer=Adam(lr=learning_rate),
              metrics=['accuracy'])

history = model.fit(X_train, Y_train,
                    batch_size=batch_size, nb_epoch=n_epochs,
                    verbose=1, validation_data=(X_test, Y_test))
score = model.evaluate(X_test, Y_test, verbose=0)
print('Test score:', score[0])
print('Test accuracy:', score[1])

60000 train samples
10000 test samples
____________________________________________________________________________________________________
Layer (type)                     Output Shape          Param #     Connected to                     
dense_10 (Dense)                 (None, 512)           401920      dense_input_4[0][0]              
____________________________________________________________________________________________________
activation_10 (Activation)       (None, 512)           0           dense_10[0][0]                   
____________________________________________________________________________________________________
dropout_7 (Dropout)              (None, 512)           0           activation_10[0][0]              
____________________________________________________________________________________________________
dense_11 (Dense)                 (None, 512)           262656      dropout_7[0][0]                  
____________________________________________________