# Setup

In [1]:
from __future__ import division
from __future__ import unicode_literals
from __future__ import print_function

import numpy as np
import tensorflow as tf

# Basic RNN cell

<img src="img/RNN-structure.png" alt="RNN structure" style="width: 800px;"/>

In [2]:
tf.reset_default_graph()

max_steps = 2
n_inputs = 3

# data shape: batch_size X sequence_length X feature_num
X = tf.placeholder(tf.float32, [None, max_steps, n_inputs])

# Basic RNN
n_neurons = 5  # hidden size for rnn cell
basic_cell = tf.contrib.rnn.BasicRNNCell(num_units=n_neurons) # X(t)*Wx + y(t-1)*Wy = y(t) 
seq_length = tf.placeholder(tf.int32, [None])
outputs, states = tf.nn.dynamic_rnn(basic_cell, X, dtype=tf.float32, sequence_length=seq_length)

init = tf.global_variables_initializer()

In [3]:
X_batch = np.array([
         # t = 0     t = 1
        [[0, 1, 2], [9, 8, 7]], # instance 0, length = 2
        [[3, 4, 5], [0, 0, 0]], # instance 1, length = 1
        [[6, 7, 8], [6, 5, 4]], # instance 2, length = 2
        [[9, 0, 1], [3, 2, 1]], # instance 3, length = 2
    ])

X_length = [2,1,2,2]

with tf.Session() as sess:
    init.run()
    outputs_val, states_val = sess.run([outputs, states], feed_dict={X: X_batch, seq_length: X_length})
    print('outputs:')
    print(outputs_val)
    print('\nstates:')
    print(states_val)

outputs:
[[[-0.94336641  0.78830135  0.93238342 -0.53071505 -0.37779272]
  [-0.99999994  0.99999964  1.         -0.97666121 -0.94991612]]

 [[-0.9999727   0.99968761  0.9999907  -0.91765964 -0.85683709]
  [ 0.          0.          0.          0.          0.        ]]

 [[-1.          0.99999964  1.         -0.98804462 -0.97401565]
  [-0.99973381  0.99932456  0.99999863 -0.84873462 -0.80149025]]

 [[-0.86643529  0.99133348  0.99977899  0.47188064  0.96711951]
  [-0.95520151  0.97891372  0.99928331  0.10864748  0.01988852]]]

states:
[[-0.99999994  0.99999964  1.         -0.97666121 -0.94991612]
 [-0.9999727   0.99968761  0.9999907  -0.91765964 -0.85683709]
 [-0.99973381  0.99932456  0.99999863 -0.84873462 -0.80149025]
 [-0.95520151  0.97891372  0.99928331  0.10864748  0.01988852]]


# RNN types 

<img src="img/RNN-types.png" alt="RNN types" style="width: 800px;"/>

# LSTM - Long Short-Term Memory

<img src="img/LSTM.png" alt="LSTM" style="width: 600px;"/>

In [4]:
#lstm_cell = tf.nn.rnn_cell.BasicLSTMCell(num_units=n_neurons)

# Deep RNN

<img src="img/RNN-deep.png" alt="Deep RNN" style="width: 600px;"/> 

In [5]:
tf.reset_default_graph()

max_steps = 2
n_inputs = 3

# data shape: batch_size X sequence_length X feature_num
X = tf.placeholder(tf.float32, [None, max_steps, n_inputs])

# Basic RNN
n_neurons = 5
n_layers = 3

lstm_cell = tf.contrib.rnn.BasicLSTMCell(num_units=n_neurons)
multi_layer_cell = tf.contrib.rnn.MultiRNNCell([basic_cell] * n_layers)
seq_length = tf.placeholder(tf.int32, [None])
outputs, states = tf.nn.dynamic_rnn(multi_layer_cell, X, dtype=tf.float32, sequence_length=seq_length)

init = tf.global_variables_initializer()

In [6]:
X_batch = np.array([
         # t = 0     t = 1
        [[0, 1, 2], [9, 8, 7]], # instance 0, length = 2
        [[3, 4, 5], [0, 0, 0]], # instance 1, length = 1
        [[6, 7, 8], [6, 5, 4]], # instance 2, length = 2
        [[9, 0, 1], [3, 2, 1]], # instance 3, length = 2
    ])

X_length = [2,1,2,2]

with tf.Session() as sess:
    init.run()
    outputs_val, states_val = sess.run([outputs, states], feed_dict={X: X_batch, seq_length: X_length})
    print('outputs:')
    print(outputs_val)
    print('\nstates:')
    for i, s in enumerate(states_val):
        print('layer {}'.format(i + 1))
        print(s)

outputs:
[[[-0.25792614 -0.15808602  0.11610406 -0.34532174 -0.17429137]
  [-0.66740745  0.08121295 -0.29551756 -0.03799359 -0.38327646]]

 [[-0.32111779 -0.17445439  0.10995026 -0.35037693 -0.16939144]
  [ 0.          0.          0.          0.          0.        ]]

 [[-0.34911358 -0.19412838  0.1064423  -0.32386175 -0.15464006]
  [-0.67758453  0.31614462 -0.38080788  0.09814353 -0.23457474]]

 [[ 0.22410728  0.25423193 -0.19750072  0.41633067  0.12349871]
  [ 0.18127856 -0.38801974  0.50288171 -0.21824214 -0.50736445]]]

states:
layer 1
[[ 0.7219075  -0.09534707 -0.98359156 -0.99862498 -0.86546892]
 [ 0.89839154  0.49845704 -0.9963544  -0.98187983  0.26582101]
 [ 0.60942096 -0.27353281 -0.5767386  -0.98241305 -0.84704751]
 [-0.92024708  0.69848144 -0.79852301  0.4837833  -0.08642693]]
layer 2
[[-0.84737265  0.46746391 -0.52890605  0.35808447 -0.3022635 ]
 [-0.60922343  0.16847374  0.15551859  0.78700322 -0.2671763 ]
 [-0.83922887  0.47185495 -0.48851815 -0.09702769 -0.39904481]
 [ 0

# Embedding before RNN 

In [7]:
from keras.preprocessing import sequence
from keras.layers.embeddings import Embedding
from keras.layers import LSTM
from keras import backend as K

Using TensorFlow backend.


## Process sequence with Keras

In [8]:
texts = [
    [1, 2, 4, 2, 3], # 我 非常 愛 你 唷
    [0, 1, 2], 
    [4, 5, 2, 1],
    [5, 2, 1, 3, 4, 1, 2, 3, 4, 5]
]

max_length = 5
pad_texts = sequence.pad_sequences(texts, maxlen=5)
print(pad_texts)

[[1 2 4 2 3]
 [0 0 0 1 2]
 [0 4 5 2 1]
 [1 2 3 4 5]]


## Embedding layer (keras as interface to tensorflow)

In [9]:
tf.reset_default_graph()

X = tf.placeholder(tf.int32, [None, max_length])

top_words = 6 # 0 ~ 5
embedding_length = 3
embedding = Embedding(input_dim=top_words, output_dim=embedding_length, input_length=max_length)(X)

init = tf.global_variables_initializer()
with tf.Session() as sess:
    init.run()
    print(embedding.eval(feed_dict={X: pad_texts}))

[[[-0.04115858 -0.00087099  0.03553173]
  [-0.00483301 -0.01721189  0.03400842]
  [-0.00439917  0.01894731 -0.04771699]
  [-0.00483301 -0.01721189  0.03400842]
  [ 0.01789529 -0.0384722   0.03360324]]

 [[ 0.03390614  0.02066951  0.01423012]
  [ 0.03390614  0.02066951  0.01423012]
  [ 0.03390614  0.02066951  0.01423012]
  [-0.04115858 -0.00087099  0.03553173]
  [-0.00483301 -0.01721189  0.03400842]]

 [[ 0.03390614  0.02066951  0.01423012]
  [-0.00439917  0.01894731 -0.04771699]
  [ 0.03371974  0.02353113  0.00150312]
  [-0.00483301 -0.01721189  0.03400842]
  [-0.04115858 -0.00087099  0.03553173]]

 [[-0.04115858 -0.00087099  0.03553173]
  [-0.00483301 -0.01721189  0.03400842]
  [ 0.01789529 -0.0384722   0.03360324]
  [-0.00439917  0.01894731 -0.04771699]
  [ 0.03371974  0.02353113  0.00150312]]]


## Embedding + LSTM 

In [10]:
tf.reset_default_graph()

X = tf.placeholder(tf.int32, [None, max_length])

# Embedding
top_words = 6 # 0 ~ 5
embedding_length = 3
embedding = Embedding(input_dim=top_words, output_dim=embedding_length, input_length=max_length)(X)

# LSTM
lstm_cell = tf.contrib.rnn.BasicLSTMCell(num_units=2)
outputs, states = tf.nn.dynamic_rnn(lstm_cell, embedding, dtype=tf.float32)

init = tf.global_variables_initializer()
with tf.Session() as sess:
    init.run()
    outputs_val, states_val = sess.run([outputs, states], feed_dict={X: pad_texts})
    print('outputs:')
    print(outputs_val)
    print('\nstates:')
    print(states_val)

outputs:
[[[  2.27748300e-03   2.54794490e-03]
  [ -6.72289636e-03   2.12552119e-03]
  [ -5.15798200e-03   2.57817283e-03]
  [ -1.18720494e-02   1.75152568e-03]
  [ -1.17209079e-02   2.15285574e-03]]

 [[ -7.16912677e-04  -4.45036776e-03]
  [ -5.85651200e-04  -8.36673286e-03]
  [  4.92734434e-05  -1.17795616e-02]
  [  3.92194884e-03  -7.55762029e-03]
  [ -4.20305226e-03  -6.66038040e-03]]

 [[ -7.16912677e-04  -4.45036776e-03]
  [ -2.09720354e-04  -2.76012183e-03]
  [  4.19360040e-05  -5.89074241e-03]
  [ -7.10867392e-03  -5.33945905e-03]
  [ -1.77819841e-03  -2.39658100e-03]]

 [[  2.27748300e-03   2.54794490e-03]
  [ -6.72289636e-03   2.12552119e-03]
  [ -8.27405322e-03   2.74330750e-03]
  [ -6.33774092e-03   3.04499455e-03]
  [ -4.98534460e-03  -1.12100574e-03]]]

states:
LSTMStateTuple(c=array([[-0.02339812,  0.00432264],
       [-0.00834949, -0.01318919],
       [-0.00356107, -0.00483211],
       [-0.0098818 , -0.00223147]], dtype=float32), h=array([[-0.01172091,  0.00215286],
   

## Replace with Keras LSTM

In [27]:
tf.reset_default_graph()

X = tf.placeholder(tf.int32, [None, max_length])

# Embedding
top_words = 6 # 0 ~ 5
embedding_length = 3
embedding = Embedding(input_dim=top_words, output_dim=embedding_length, input_length=max_length)(X)

# LSTM
outputs = LSTM(2, return_sequences=True)(embedding)

init = tf.global_variables_initializer()
with tf.Session() as sess:
    init.run()
    outputs_val = sess.run(outputs, feed_dict={X: pad_texts})
    print(outputs_val)

[[[-0.0092869   0.00178546]
  [-0.02605121  0.00459695]
  [-0.02878794  0.00521053]
  [-0.04146672  0.00858775]
  [-0.0255339   0.00482388]]

 [[-0.00984028  0.00317693]
  [-0.01728653  0.00655342]
  [-0.02271022  0.0100574 ]
  [-0.02586466  0.01219606]
  [-0.0374227   0.0150606 ]]

 [[-0.00984028  0.00317693]
  [-0.01579443  0.00325947]
  [-0.02110537  0.00349698]
  [-0.03553843  0.00662705]
  [-0.03701945  0.00943947]]

 [[-0.0092869   0.00178546]
  [-0.02605121  0.00459695]
  [-0.01381799  0.00033406]
  [-0.0200562   0.00070674]
  [-0.02532266  0.00114754]]]
