# Setup

In [1]:
from __future__ import division
from __future__ import unicode_literals
from __future__ import print_function

import numpy as np
import tensorflow as tf

# Basic RNN cell

<img src="img/RNN-structure.png" alt="RNN structure" style="width: 800px;"/>

In [2]:
tf.reset_default_graph()

max_steps = 2
n_inputs = 3

# data shape: batch_size X sequence_length X feature_num
X = tf.placeholder(tf.float32, [None, max_steps, n_inputs])

# Basic RNN
n_neurons = 5  # hidden size for rnn cell
basic_cell = tf.contrib.rnn.BasicRNNCell(num_units=n_neurons) # X(t)*Wx + y(t-1)*Wy = y(t) 
seq_length = tf.placeholder(tf.int32, [None])
outputs, states = tf.nn.dynamic_rnn(basic_cell, X, dtype=tf.float32, sequence_length=seq_length)

init = tf.global_variables_initializer()

In [3]:
X_batch = np.array([
         # t = 0     t = 1
        [[0, 1, 2], [9, 8, 7]], # instance 0, length = 2
        [[3, 4, 5], [0, 0, 0]], # instance 1, length = 1
        [[6, 7, 8], [6, 5, 4]], # instance 2, length = 2
        [[9, 0, 1], [3, 2, 1]], # instance 3, length = 2
    ])

X_length = [2,1,2,2]

with tf.Session() as sess:
    init.run()
    outputs_val, states_val = sess.run([outputs, states], feed_dict={X: X_batch, seq_length: X_length})
    print('outputs:')
    print(outputs_val)
    print('\nstates:')
    print(states_val)

outputs:
[[[ 0.07388831  0.83327669 -0.92938942  0.65999997  0.32705325]
  [-0.99995208  0.99999964 -0.99987948 -0.90367883  0.34513646]]

 [[-0.91396397  0.99929625 -0.99860328  0.64561605  0.5721463 ]
  [ 0.          0.          0.          0.          0.        ]]

 [[-0.99652094  0.99999738 -0.99997348  0.63075882  0.74511898]
  [-0.99873692  0.99980426 -0.9988488  -0.86127239  0.34120306]]

 [[-0.99899191  0.71895832  0.99938679 -0.99996424 -0.99846786]
  [-0.96630585  0.91309631  0.11886316  0.46950158  0.32660544]]]

states:
[[-0.99995208  0.99999964 -0.99987948 -0.90367883  0.34513646]
 [-0.91396397  0.99929625 -0.99860328  0.64561605  0.5721463 ]
 [-0.99873692  0.99980426 -0.9988488  -0.86127239  0.34120306]
 [-0.96630585  0.91309631  0.11886316  0.46950158  0.32660544]]


# RNN types 

<img src="img/RNN-types.png" alt="RNN types" style="width: 800px;"/>

# LSTM - Long Short-Term Memory

<img src="img/LSTM.png" alt="LSTM" style="width: 600px;"/>

In [4]:
#lstm_cell = tf.nn.rnn_cell.BasicLSTMCell(num_units=n_neurons)

# Deep RNN

<img src="img/RNN-deep.png" alt="Deep RNN" style="width: 600px;"/> 

In [5]:
tf.reset_default_graph()

max_steps = 2
n_inputs = 3

# data shape: batch_size X sequence_length X feature_num
X = tf.placeholder(tf.float32, [None, max_steps, n_inputs])

# Basic RNN
n_neurons = 5
n_layers = 3

lstm_cell = tf.contrib.rnn.BasicLSTMCell(num_units=n_neurons)
multi_layer_cell = tf.contrib.rnn.MultiRNNCell([basic_cell] * n_layers)
seq_length = tf.placeholder(tf.int32, [None])
outputs, states = tf.nn.dynamic_rnn(multi_layer_cell, X, dtype=tf.float32, sequence_length=seq_length)

init = tf.global_variables_initializer()

In [6]:
X_batch = np.array([
         # t = 0     t = 1
        [[0, 1, 2], [9, 8, 7]], # instance 0, length = 2
        [[3, 4, 5], [0, 0, 0]], # instance 1, length = 1
        [[6, 7, 8], [6, 5, 4]], # instance 2, length = 2
        [[9, 0, 1], [3, 2, 1]], # instance 3, length = 2
    ])

X_length = [2,1,2,2]

with tf.Session() as sess:
    init.run()
    outputs_val, states_val = sess.run([outputs, states], feed_dict={X: X_batch, seq_length: X_length})
    print('outputs:')
    print(outputs_val)
    print('\nstates:')
    for i, s in enumerate(states_val):
        print('layer {}'.format(i + 1))
        print(s)

outputs:
[[[-0.30183983 -0.53327268 -0.17626247  0.18664394 -0.0069315 ]
  [ 0.13133709 -0.7593841   0.10228386  0.76015329  0.03787287]]

 [[-0.40445489 -0.52822912 -0.15684663  0.39030898  0.05710426]
  [ 0.          0.          0.          0.          0.        ]]

 [[-0.42082024 -0.50986516 -0.16582783  0.42077854  0.0718665 ]
  [ 0.2561976  -0.69520563  0.40204772  0.78219736 -0.0561308 ]]

 [[ 0.27107078 -0.07842363  0.33445096  0.31843457  0.01669742]
  [ 0.82530582 -0.15954629  0.46029335  0.63888782 -0.07108143]]]

states:
layer 1
[[-1.          0.99747026  0.93127561  0.5574705   0.94813067]
 [-0.99987203  0.87718564  0.98404205 -0.73622203  0.78220993]
 [-0.99997163  0.89926952 -0.37906125  0.67388755  0.76403129]
 [-0.96757096 -0.12766157  0.49969807  0.96959639  0.88902229]]
layer 2
[[ 0.59466916 -0.54594117  0.81721985  0.78625739  0.89290899]
 [ 0.70465624 -0.42469725  0.31548288 -0.20719554  0.82733977]
 [ 0.29520756 -0.09792763  0.88097161  0.89828491  0.77829367]
 [-0

# Embedding before RNN 

In [7]:
from keras.preprocessing import sequence
from keras.layers.embeddings import Embedding
from keras.layers import LSTM
from keras import backend as K

Using TensorFlow backend.


## Process sequence with Keras

In [8]:
texts = [
    [1, 2, 4, 2, 3], # 我 非常 愛 你 唷
    [0, 1, 2], 
    [4, 5, 2, 1],
    [5, 2, 1, 3, 4, 1, 2, 3, 4, 5]
]

max_length = 5
pad_texts = sequence.pad_sequences(texts, maxlen=5)
print(pad_texts)

[[1 2 4 2 3]
 [0 0 0 1 2]
 [0 4 5 2 1]
 [1 2 3 4 5]]


## Embedding layer (keras as interface to tensorflow)

In [9]:
tf.reset_default_graph()

X = tf.placeholder(tf.int32, [None, max_length])

top_words = 6 # 0 ~ 5
embedding_length = 3
embedding = Embedding(input_dim=top_words, output_dim=embedding_length, input_length=max_length)(X)

init = tf.global_variables_initializer()
with tf.Session() as sess:
    init.run()
    print(embedding.eval(feed_dict={X: pad_texts}))

[[[ 0.02795983  0.02821353  0.04689256]
  [-0.04656286  0.0403927   0.03845784]
  [-0.00709755 -0.03114094 -0.00675856]
  [-0.04656286  0.0403927   0.03845784]
  [ 0.02828236  0.0426243  -0.00267712]]

 [[ 0.01448289  0.02166584  0.00406395]
  [ 0.01448289  0.02166584  0.00406395]
  [ 0.01448289  0.02166584  0.00406395]
  [ 0.02795983  0.02821353  0.04689256]
  [-0.04656286  0.0403927   0.03845784]]

 [[ 0.01448289  0.02166584  0.00406395]
  [-0.00709755 -0.03114094 -0.00675856]
  [ 0.00649448 -0.01626713 -0.01955664]
  [-0.04656286  0.0403927   0.03845784]
  [ 0.02795983  0.02821353  0.04689256]]

 [[ 0.02795983  0.02821353  0.04689256]
  [-0.04656286  0.0403927   0.03845784]
  [ 0.02828236  0.0426243  -0.00267712]
  [-0.00709755 -0.03114094 -0.00675856]
  [ 0.00649448 -0.01626713 -0.01955664]]]


## Embedding + LSTM 

In [14]:
tf.reset_default_graph()

X = tf.placeholder(tf.int32, [None, max_length])

# Embedding
top_words = 6 # 0 ~ 5
embedding_length = 3
embedding = Embedding(input_dim=top_words, output_dim=embedding_length, input_length=max_length)(X)

# LSTM
lstm_cell = tf.contrib.rnn.BasicLSTMCell(num_units=2)
outputs, states = tf.nn.dynamic_rnn(lstm_cell, embedding, dtype=tf.float32)

init = tf.global_variables_initializer()
with tf.Session() as sess:
    init.run()
    outputs_val, states_val = sess.run([outputs, states], feed_dict={X: pad_texts})
    print('outputs:')
    print(outputs_val)
    print('\nstates:')
    print(states_val) # c: states_val[0], long-term, h: states_val[1], short-term (result) 

outputs:
[[[  5.23487525e-03   2.93326052e-03]
  [ -3.99231398e-03  -2.89404648e-03]
  [ -5.82309719e-03  -3.70874559e-03]
  [ -9.44848359e-03  -7.16878520e-03]
  [ -3.46902059e-03  -5.17792813e-03]]

 [[  4.40151477e-03   7.06857885e-04]
  [  6.83350209e-03   7.70605111e-04]
  [  8.21824092e-03   5.26803546e-04]
  [  9.87391826e-03   2.35701539e-03]
  [ -1.32134371e-03  -3.91992414e-03]]

 [[  4.40151477e-03   7.06857885e-04]
  [ -1.54581759e-03  -1.64780370e-03]
  [ -1.19421538e-03  -6.20696228e-05]
  [ -7.24426657e-03  -4.63420339e-03]
  [  1.64141145e-03  -2.07956109e-04]]

 [[  5.23487525e-03   2.93326052e-03]
  [ -3.99231398e-03  -2.89404648e-03]
  [ -8.89721443e-04  -2.15966930e-03]
  [ -4.16075531e-03  -3.43416282e-03]
  [ -2.48068268e-03  -1.28060323e-03]]]

states:
LSTMStateTuple(c=array([[-0.0069551 , -0.01032648],
       [-0.00265441, -0.0079504 ],
       [ 0.00327387, -0.00041221],
       [-0.00494373, -0.00254638]], dtype=float32), h=array([[-0.00346902, -0.00517793],
   

## Replace with Keras LSTM

In [11]:
tf.reset_default_graph()

X = tf.placeholder(tf.int32, [None, max_length])

# Embedding
top_words = 6 # 0 ~ 5
embedding_length = 3
embedding = Embedding(input_dim=top_words, output_dim=embedding_length, input_length=max_length)(X)

# LSTM
outputs = LSTM(2, return_sequences=True)(embedding)

init = tf.global_variables_initializer()
with tf.Session() as sess:
    init.run()
    outputs_val = sess.run(outputs, feed_dict={X: pad_texts})
    print(outputs_val)

[[[-0.00398481 -0.00284151]
  [-0.01287368 -0.0047118 ]
  [-0.00586984 -0.00344549]
  [-0.01399477 -0.00500292]
  [-0.00138086 -0.00590383]]

 [[ 0.00885494  0.00543   ]
  [ 0.01414005  0.00956309]
  [ 0.01745504  0.01291808]
  [ 0.00738959  0.00708744]
  [-0.00542119  0.00340092]]

 [[ 0.00885494  0.00543   ]
  [ 0.00648394  0.00357731]
  [ 0.0017614   0.01603111]
  [-0.00642674  0.01283678]
  [-0.00457685  0.01093406]]

 [[-0.00398481 -0.00284151]
  [-0.01287368 -0.0047118 ]
  [-0.00080796 -0.0057631 ]
  [-0.00047308 -0.00605654]
  [-0.00331537  0.00746535]]]
